"""
X402RequestTool: AIKit tool wrapper for X402 signed requests.

Implements Issue #74: AIKit x402.request Tool Wrapper

Per PRD Section 8 (AIKit Integration):
- Standardized tool abstraction for X402 request signing and submission
- Automatic event logging and memory storage
- DID-based signature verification
- Integration with agent workflows

Architecture:
- Inherits from BaseTool for standardized behavior
- Wraps X402Service for request creation
- Integrates DIDSigner for signature verification
- Automatically logs to events API
- Automatically stores in agent_memory

Usage:
    tool = X402RequestTool(event_service=event_service, memory_service=memory_service)

    context = ToolExecutionContext(
        project_id="proj_123",
        agent_id="did:ethr:0xtransaction001",
        run_id="run_456",
        task_id="task_789"
    )

    result = await tool.execute(
        context=context,
        did="did:ethr:0xtransaction001",
        signature="0xsignature123...",
        payload={
            "type": "payment_authorization",
            "amount": "100.00",
            "currency": "USD",
            "recipient": "did:ethr:0xrecipient123"
        }
    )

    if result.success:
        print(f"X402 Request ID: {result.data['request_id']}")
    else:
        print(f"Error: {result.error}")
"""

import logging
from typing import Any, Dict, Optional
from tools.base import BaseTool, ToolExecutionContext, ToolResult
from app.services.x402_service import x402_service
from app.core.did_signer import DIDSigner, InvalidDIDError
from app.schemas.x402_requests import X402RequestStatus

logger = logging.getLogger(__name__)


class X402RequestTool(BaseTool):
    """
    AIKit tool wrapper for X402 signed request submission.

    Per PRD Section 8:
    - Tool name: "x402.request"
    - Parameters: did, signature, payload
    - Runtime: FastAPI backend
    - Automatically traced and logged
    - Shared across all agents

    Security (Issue #75):
    - Verifies ECDSA signature against agent DID
    - Rejects invalid signatures
    - Logs verification failures

    Integration:
    - Calls X402Service for request creation
    - Stores result in agent_memory
    - Logs events for audit trail
    """

    def __init__(
        self,
        event_service: Optional[Any] = None,
        memory_service: Optional[Any] = None
    ):
        """
        Initialize X402RequestTool.

        Args:
            event_service: EventService instance (optional)
            memory_service: AgentMemoryService instance (optional)
        """
        super().__init__(event_service=event_service, memory_service=memory_service)

    @property
    def name(self) -> str:
        """
        Tool name per PRD Section 8.

        Returns:
            "x402.request"
        """
        return "x402.request"

    @property
    def description(self) -> str:
        """
        Human-readable tool description.

        Returns:
            Tool description for agent use
        """
        return (
            "Submit a signed X402 payment request. "
            "Verifies DID signature and creates traceable payment authorization. "
            "Required parameters: did (agent DID), signature (ECDSA hex signature), "
            "payload (X402 protocol payment details)."
        )

    @property
    def schema(self) -> Dict[str, Any]:
        """
        Tool parameter schema per PRD Section 8.

        Returns:
            JSON Schema for tool parameters
        """
        return {
            "type": "object",
            "properties": {
                "did": {
                    "type": "string",
                    "description": (
                        "Agent DID (Decentralized Identifier) that signs the request. "
                        "Format: did:ethr:0x... "
                        "Used for signature verification."
                    ),
                    "pattern": "^did:ethr:0x[a-fA-F0-9]{40}$"
                },
                "signature": {
                    "type": "string",
                    "description": (
                        "ECDSA signature of the payload in hex format. "
                        "Format: 0x... "
                        "Generated by agent's private key."
                    ),
                    "pattern": "^0x[a-fA-F0-9]+$"
                },
                "payload": {
                    "type": "object",
                    "description": (
                        "X402 protocol request payload. "
                        "Contains payment authorization details: "
                        "type, amount, currency, recipient, memo, etc."
                    ),
                    "properties": {
                        "type": {
                            "type": "string",
                            "description": "Request type (e.g., 'payment_authorization')"
                        },
                        "amount": {
                            "type": "string",
                            "description": "Payment amount as string (e.g., '100.00')"
                        },
                        "currency": {
                            "type": "string",
                            "description": "Currency code (e.g., 'USD', 'EUR')"
                        },
                        "recipient": {
                            "type": "string",
                            "description": "Recipient DID"
                        }
                    }
                },
                "linked_memory_ids": {
                    "type": "array",
                    "description": "Optional list of agent_memory IDs to link",
                    "items": {"type": "string"}
                },
                "linked_compliance_ids": {
                    "type": "array",
                    "description": "Optional list of compliance_event IDs to link",
                    "items": {"type": "string"}
                }
            },
            "required": ["did", "signature", "payload"]
        }

    async def _execute(
        self,
        context: ToolExecutionContext,
        **parameters: Any
    ) -> ToolResult:
        """
        Execute the X402 request tool.

        Workflow:
        1. Validate required parameters
        2. Verify DID signature
        3. Create X402 request via service
        4. Return structured result

        Args:
            context: Execution context (project, agent, run, task IDs)
            **parameters: Tool parameters (did, signature, payload)

        Returns:
            ToolResult with success/error and request data

        Raises:
            No exceptions raised - errors returned in ToolResult
        """
        try:
            # Validate required parameters
            did = parameters.get("did")
            signature = parameters.get("signature")
            payload = parameters.get("payload")

            if not did:
                return ToolResult(
                    success=False,
                    error="Missing required parameter: 'did'",
                    metadata={"tool_name": self.name}
                )

            if not signature:
                return ToolResult(
                    success=False,
                    error="Missing required parameter: 'signature'",
                    metadata={"tool_name": self.name}
                )

            if not payload:
                return ToolResult(
                    success=False,
                    error="Missing required parameter: 'payload'",
                    metadata={"tool_name": self.name}
                )

            # Validate payload is not empty
            if not isinstance(payload, dict) or len(payload) == 0:
                return ToolResult(
                    success=False,
                    error="Parameter 'payload' must be a non-empty dictionary",
                    metadata={"tool_name": self.name}
                )

            # Verify DID signature (Issue #75)
            try:
                is_valid = DIDSigner.verify_signature(
                    payload=payload,
                    signature_hex=signature,
                    did=did
                )

                if not is_valid:
                    logger.warning(
                        f"Invalid signature for DID {did}",
                        extra={
                            "tool_name": self.name,
                            "agent_id": context.agent_id,
                            "did": did
                        }
                    )
                    return ToolResult(
                        success=False,
                        error="Invalid signature: signature verification failed",
                        metadata={
                            "tool_name": self.name,
                            "did": did,
                            "verification_status": "failed"
                        }
                    )

                logger.info(
                    f"Signature verified successfully for DID {did}",
                    extra={
                        "tool_name": self.name,
                        "agent_id": context.agent_id,
                        "did": did
                    }
                )

            except InvalidDIDError as e:
                logger.error(
                    f"Invalid DID format: {did}",
                    extra={
                        "tool_name": self.name,
                        "agent_id": context.agent_id,
                        "did": did,
                        "error": str(e)
                    }
                )
                return ToolResult(
                    success=False,
                    error=f"Invalid DID format: {str(e)}",
                    metadata={
                        "tool_name": self.name,
                        "did": did,
                        "error_type": "InvalidDIDError"
                    }
                )

            except Exception as e:
                logger.error(
                    f"Signature verification error: {str(e)}",
                    extra={
                        "tool_name": self.name,
                        "agent_id": context.agent_id,
                        "did": did,
                        "error": str(e)
                    },
                    exc_info=True
                )
                return ToolResult(
                    success=False,
                    error=f"Signature verification error: {str(e)}",
                    metadata={
                        "tool_name": self.name,
                        "error_type": type(e).__name__
                    }
                )

            # Create X402 request via service
            try:
                # Get optional parameters
                linked_memory_ids = parameters.get("linked_memory_ids", [])
                linked_compliance_ids = parameters.get("linked_compliance_ids", [])

                # Add signature verification metadata
                metadata = {
                    "signature_verified": True,
                    "verification_did": did,
                    "tool_name": self.name,
                    "correlation_id": context.correlation_id
                }

                request_data = await x402_service.create_request(
                    project_id=context.project_id,
                    agent_id=context.agent_id,
                    task_id=context.task_id or "unknown",
                    run_id=context.run_id,
                    request_payload=payload,
                    signature=signature,
                    status=X402RequestStatus.PENDING,
                    linked_memory_ids=linked_memory_ids,
                    linked_compliance_ids=linked_compliance_ids,
                    metadata=metadata
                )

                logger.info(
                    f"X402 request created: {request_data['request_id']}",
                    extra={
                        "tool_name": self.name,
                        "agent_id": context.agent_id,
                        "request_id": request_data["request_id"],
                        "run_id": context.run_id
                    }
                )

                return ToolResult(
                    success=True,
                    data=request_data,
                    metadata={
                        "tool_name": self.name,
                        "request_id": request_data["request_id"],
                        "verification_status": "verified"
                    }
                )

            except Exception as e:
                logger.error(
                    f"Failed to create X402 request: {str(e)}",
                    extra={
                        "tool_name": self.name,
                        "agent_id": context.agent_id,
                        "error": str(e)
                    },
                    exc_info=True
                )
                return ToolResult(
                    success=False,
                    error=f"Failed to create X402 request: {str(e)}",
                    metadata={
                        "tool_name": self.name,
                        "error_type": type(e).__name__
                    }
                )

        except Exception as e:
            # Catch-all for unexpected errors
            logger.error(
                f"Unexpected error in X402RequestTool: {str(e)}",
                extra={
                    "tool_name": self.name,
                    "agent_id": context.agent_id
                },
                exc_info=True
            )
            return ToolResult(
                success=False,
                error=f"Unexpected error: {str(e)}",
                metadata={
                    "tool_name": self.name,
                    "error_type": type(e).__name__
                }
            )
